-- MySQL Script generated by MySQL Workbench
-- mar 24 abr 2018 02:00:54 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema votacionesUnimag
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema votacionesUnimag
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `votacionesUnimag` DEFAULT CHARACTER SET utf8 ;
USE `votacionesUnimag` ;

-- -----------------------------------------------------
-- Table `votacionesUnimag`.`facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `votacionesUnimag`.`facultad` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `votacionesUnimag`.`mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `votacionesUnimag`.`mesa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `votacionesUnimag`.`programa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `votacionesUnimag`.`programa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `facultad_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_programa_facultad1_idx` (`facultad_id` ASC),
  CONSTRAINT `fk_programa_facultad1`
    FOREIGN KEY (`facultad_id`)
    REFERENCES `votacionesUnimag`.`facultad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `votacionesUnimag`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `votacionesUnimag`.`rol` (
  `id` VARCHAR(4) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `rol` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `votacionesUnimag`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `votacionesUnimag`.`usuario` (
  `codigo` INT(12) NOT NULL,
  `nombre1` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `nombre2` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `apellido1` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `apellido2` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `password` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `rol_id` VARCHAR(4) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `mesa_id` INT(11) NULL DEFAULT NULL,
  `programa_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_usuario_rol_idx` (`rol_id` ASC),
  INDEX `fk_usuario_mesa1_idx` (`mesa_id` ASC),
  INDEX `fk_usuario_programa1_idx` (`programa_id` ASC),
  CONSTRAINT `fk_usuario_mesa1`
    FOREIGN KEY (`mesa_id`)
    REFERENCES `votacionesUnimag`.`mesa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_programa1`
    FOREIGN KEY (`programa_id`)
    REFERENCES `votacionesUnimag`.`programa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `votacionesUnimag`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
